#!/bin/bash

getPermission="sudo "
readonly getPermission

logFile="pythonModulesBatchInstall-successful.log"
readonly logFile

touch $logFile

$getPermission pip install shutil
$getPermission pip install crontab
$getPermission pip install contextmanger
$getPermission pip install multiprocessing
$getPermission pip install bottle
$getPermission pip install argparse
$getPermission pip install collections
$getPermission pip install functools
$getPermission pip install glob
$getPermission pip install os
$getPermission pip install queue
$getPermission pip install simplehttpserver
$getPermission pip install subprocess
$getPermission pip install threading
$getPermission pip install requests
$getPermission pip install bs4
$getPermission pip install csv
$getPermission pip install pymongo
$getPermission pip install MySQL-python
$getPermission pip install gevent
$getPermission pip install numpy
$getPermission pip install pandas
$getPermission pip install scipy
$getPermission pip install sympy
$getPermission pip install statsmodels
$getPermission pip install nltk
$getPermission pip install time
$getPermission pip install random
$getPermission pip install sys
$getPermission pip install xml
$getPermission pip install pyyam
$getPermission pip install configparser
$getPermission pip install hashlib
$getPermission pip install re
$getPermission pip install itertools
$getPermission pip install pdb
$getPermission pip install traceback
$getPermission pip install pprint
$getPermission pip install logging
$getPermission pip install urllib
$getPermission pip install urllib2
$getPermission pip install httplib
$getPermission pip install pickle
$getPermission pip install cpickle
$getPermission pip install md5
$getPermission pip install sha
$getPermission pip install json
$getPermission pip install simplejson
$getPermission pip install timeit
$getPermission pip install cprofile
$getPermission pip install glob
$getPermission pip install atexit
$getPermission pip install dis
$getPermission pip install paramiko
$getPermission pip install selenium
$getPermission pip install lxml
$getPermission pip install mechanize
$getPermission pip install pycurl
$getPermission pip install fabric
$getPermission pip install xmltodict
$getPermission pip install urllib3
$getPermission pip install flask
$getPermission pip install ipdb
$getPermission pip install redis
$getPermission pip install mako
$getPermission pip install pil
$getPermission pip install matplotlib
$getPermission pip install scrapy
$getPermission pip install django
$getPermission pip install tornado
$getPermission pip install sh
$getPermission pip install suds
$getPermission pip install seaborn
$getPermission pip install plotly
$getPermission pip install bokeh
$getPermission pip install pydot
$getPermission pip install scikit-learn
$getPermission pip install xgboost
$getPermission pip install lightgbm
$getPermission pip install catboost
$getPermission pip install eli5
$getPermission pip install tensorflow
$getPermission pip install pytorch
$getPermission pip install keras
$getPermission pip install dist-keras
$getPermission pip install elephas
$getPermission pip install spark-deep-learning
$getPermission pip install spacy
$getPermission pip install gensim
$getPermission pip install wxpython
$getPermission pip install pillow
$getPermission pip install sqlalchemy
$getPermission pip install beautifulsoup
$getPermission pip install twisted
$getPermission pip install pygame
$getPermission pip install pyglet
$getPermission pip install pyqt
$getPermission pip install pygtk
$getPermission pip install scapy
$getPermission pip install pywin32
$getPermission pip install nose
$getPermission pip install ipython
$getPermission pip install math
$getPermission pip install datetime
$getPermission pip install psutil
$getPermission pip install dnspython
$getPermission pip install difflib
$getPermission pip install filecmp
$getPermission pip install smtplib
$getPermission pip install xlsxwriter
$getPermission pip install rrdtool
$getPermission pip install pyclamad
$getPermission pip install pexpect
$getPermission pip install ggihttprequesthandler
$getPermission pip install ansible
$getPermission pip install yaml
$getPermission pip install playbook
$getPermission pip install saltstack
$getPermission pip install func
$getPermission pip install builtin
$getPermission pip install exceptions
$getPermission pip install stat
$getPermission pip install string
$getPermission pip install cmath
$getPermission pip install operator
$getPermission pip install copy
$getPermission pip install types
$getPermission pip install gc
$getPermission pip install fileinput
$getPermission pip install tempfile
$getPermission pip install stringio
$getPermission pip install cstringio
$getPermission pip install mmap
$getPermission pip install userdict
$getPermission pip install userlist
$getPermission pip install errno
$getPermission pip install getopt
$getPermission pip install getpass
$getPermission pip install fnmatch
$getPermission pip install whrandom
$getPermission pip install cryopt
$getPermission pip install rotor
$getPermission pip install zlib
$getPermission pip install code
$getPermission pip install thread
$getPermission pip install commands
$getPermission pip install pipes
$getPermission pip install popen2
$getPermission pip install signal
$getPermission pip install array
$getPermission pip install struct
$getPermission pip install sdrlib
$getPermission pip install mashal
$getPermission pip install copy_reg
$getPermission pip install repr
$getPermission pip install base64
$getPermission pip install binhex
$getPermission pip install quopri
$getPermission pip install uu
$getPermission pip install binascii
$getPermission pip install xml.parsers.expat
$getPermission pip install sgmllib
$getPermission pip install htmllib
$getPermission pip install htmlentitydefs
$getPermission pip install dormatter
$getPermission pip install netrc
$getPermission pip install shlex
$getPermission pip install zipfile
$getPermission pip install gzip
$getPermission pip install rfc822
$getPermission pip install mimetools
$getPermission pip install mimewriter
$getPermission pip install mailbox
$getPermission pip install mailcap
$getPermission pip install mimetypes
$getPermission pip install packmail
$getPermission pip install mimify
$getPermission pip install multifile
$getPermission pip install socket
$getPermission pip install select
$getPermission pip install asyncore
$getPermission pip install asynchat
$getPermission pip install cookie
$getPermission pip install robotparser
$getPermission pip install ftplib
$getPermission pip install gopherlib
$getPermission pip install poplib
$getPermission pip install imaplib
$getPermission pip install telnetlib
$getPermission pip install nntplib
$getPermission pip install socketserver
$getPermission pip install basehttpserver
$getPermission pip install cgihttpserver
$getPermission pip install cgi
$getPermission pip install webbrowser
$getPermission pip install locale
$getPermission pip install unicodedata
$getPermission pip install ucnhash
$getPermission pip install imghdr
$getPermission pip install sndhdr
$getPermission pip install whatsound
$getPermission pip install aifc
$getPermission pip install sunau
$getPermission pip install sunaudio
$getPermission pip install wave
$getPermission pip install audiodev
$getPermission pip install winsound
$getPermission pip install anydbm
$getPermission pip install whichdb
$getPermission pip install shelve
$getPermission pip install dbhash
$getPermission pip install dbm
$getPermission pip install dumbdbm
$getPermission pip install gdbm
$getPermission pip install bdb
$getPermission pip install profile
$getPermission pip install pstats
$getPermission pip install tabnanny
$getPermission pip install fcntl
$getPermission pip install pwd
$getPermission pip install grp
$getPermission pip install nix
$getPermission pip install curses
$getPermission pip install termios
$getPermission pip install tty
$getPermission pip install resource
$getPermission pip install syslog
$getPermission pip install msvcrt
$getPermission pip install nt
$getPermission pip install _winreg
$getPermission pip install winreg
$getPermission pip install winreg
$getPermission pip install posix
$getPermission pip install dospath
$getPermission pip install macpath
$getPermission pip install ntpath
$getPermission pip install posixpath
$getPermission pip install strop
$getPermission pip install imp
$getPermission pip install new
$getPermission pip install pre
$getPermission pip install sre
$getPermission pip install py_compile
$getPermission pip install compileall
$getPermission pip install ihooks
$getPermission pip install linecache
$getPermission pip install macurl2path
$getPermission pip install tokenize
$getPermission pip install keyword
$getPermission pip install symbol
$getPermission pip install token
$getPermission pip install pyclbr
$getPermission pip install cmd
$getPermission pip install rexec
$getPermission pip install bastion
$getPermission pip install Bastion
$getPermission pip install readline
$getPermission pip install rlcompleter
$getPermission pip install statvfs
$getPermission pip install calendar
$getPermission pip install sched
$getPermission pip install statcache
$getPermission pip install grep
$getPermission pip install dircache
$getPermission pip install dircmp
$getPermission pip install cmp
$getPermission pip install cmpcache
$getPermission pip install util
$getPermission pip install soundex
$getPermission pip install timing
$getPermission pip install posixfile
$getPermission pip install bisect
$getPermission pip install knee
$getPermission pip install tzparse
$getPermission pip install regex
$getPermission pip install regsub
$getPermission pip install reconvert
$getPermission pip install regex_syntax
$getPermission pip install find
$getPermission pip install textwrap
$getPermission pip install stringprep
$getPermission pip install codecs
$getPermission pip install collections.abc
$getPermission pip install heapq
$getPermission pip install weakref
$getPermission pip install reprlib
$getPermission pip install numbers
$getPermission pip install fractions
$getPermission pip install decimal
$getPermission pip install stat
$getPermission pip install copyreg
$getPermission pip install marshal
$getPermission pip install sqlite3
$getPermission pip install zlib
$getPermission pip install bz2
$getPermission pip install lzma
$getPermission pip install tarfile
$getPermission pip install xdrlib
$getPermission pip install plistlib
$getPermission pip install hmac
$getPermission pip install optparser
$getPermission pip install platform
$getPermission pip install ctypes
$getPermission pip install concurrent
$getPermission pip install dummy_threading
$getPermission pip install _thread
$getPermission pip install _dummy_thread
$getPermission pip install ssl
$getPermission pip install email
$getPermission pip install html
$getPermission pip install wsgiref
$getPermission pip install http
$getPermission pip install smtpd
$getPermission pip install uuid
$getPermission pip install xmlrpc
$getPermission pip install ipaddress
$getPermission pip install audioop
$getPermission pip install chunk
$getPermission pip install colorsys
$getPermission pip install ossaudiodev
$getPermission pip install gettext
$getPermission pip install turtle
$getPermission pip install tkinter
$getPermission pip install tkinter.ttk
$getPermission pip install pydoc
$getPermission pip install doctest
$getPermission pip install unittest
$getPermission pip install test
$getPermission pip install venv
$getPermission pip install faulthandler
$getPermission pip install trace
$getPermission pip install sysconfig
$getPermission pip install main
$getPermission pip install warnings
$getPermission pip install contextlib
$getPermission pip install abc
$getPermission pip install atexit
$getPermission pip install future
$getPermission pip install inspect
$getPermission pip install site
$getPermission pip install fpectl
$getPermission pip install distutils
$getPermission pip install codeop
$getPermission pip install zipimport
$getPermission pip install pkgutil
$getPermission pip install modulefinder
$getPermission pip install runpy
$getPermission pip install importlib
$getPermission pip install ast
$getPermission pip install symtable
$getPermission pip install tabnany
$getPermission pip install formatter
$getPermission pip install msilib
$getPermission pip install spwd
$getPermission pip install crypt
$getPermission pip install pty
$getPermission pip install nis
$getPermission pip install opencv-python
$getPermission pip install mysql-python
$getPermission pip install agate
$getPermission pip install agate-dbf
$getPermission pip install agate-excel
$getPermission pip install agate-sql
$getPermission pip install Babel
$getPermission pip install csvkit
$getPermission pip install dbfread
$getPermission pip install et-xmlfile
$getPermission pip install isodate
$getPermission pip install jdcal
$getPermission pip install leather
$getPermission pip install openpyxl
$getPermission pip install parsedatetime
$getPermission pip install python-slugify
$getPermission pip install pytimeparse
$getPermission pip install pytz
$getPermission pip install six
$getPermission pip install SQLAlchemy
$getPermission pip install text-unidecode
$getPermission pip install xlrd
$getPermission pip install -lxc
$getPermission pip install lxc
$getPermission pip install cached-property
$getPermission pip install chardet
$getPermission pip install docker
$getPermission pip install docker-compose
$getPermission pip install docker-pycreds
$getPermission pip install dockerpty
$getPermission pip install docopt
$getPermission pip install httplib2
$getPermission pip install idna
$getPermission pip install jsonschema
$getPermission pip install NetEase-MusicBox
$getPermission pip install openshot-qt
$getPermission pip install pip
$getPermission pip install pycryptodomex
$getPermission pip install PyQt5
$getPermission pip install PyQt5-sip
$getPermission pip install PySocks
$getPermission pip install PyYAML
$getPermission pip install pyzmq
$getPermission pip install requests-cache
$getPermission pip install setuptools
$getPermission pip install six
$getPermission pip install texttable
$getPermission pip install websocket-client
$getPermission pip install wheel
$getPermission pip install slsx2csv
