#!/bin/bash

getPermission="sudo "
readonly getPermission

pipVersion=""

#logFile="pythonModulesBatchInstall-successful.log"
#readonly logFile

exec_Times=6
i=1

#touch $logFile

while [ $i -le ${exec_Times} ]
do
	if [[ $i -le 3 ]]
	then
		pipVersion="pip"
	else
		pipVersion="pip3"
	fi

	$getPermission ${pipVersion} install cx_Oracle
	$getPermission ${pipVersion} install filetype
	$getPermission ${pipVersion} install memory_profiler
	$getPermission ${pipVersion} install shutil
	$getPermission ${pipVersion} install crontab
	$getPermission ${pipVersion} install contextmanger
	$getPermission ${pipVersion} install multiprocessing
	$getPermission ${pipVersion} install bottle
	$getPermission ${pipVersion} install argparse
	$getPermission ${pipVersion} install collections
	$getPermission ${pipVersion} install functools
	$getPermission ${pipVersion} install glob
	$getPermission ${pipVersion} install os
	$getPermission ${pipVersion} install queue
	$getPermission ${pipVersion} install simplehttpserver
	$getPermission ${pipVersion} install subprocess
	$getPermission ${pipVersion} install threading
	$getPermission ${pipVersion} install requests
	$getPermission ${pipVersion} install bs4
	$getPermission ${pipVersion} install csv
	$getPermission ${pipVersion} install pymongo
	$getPermission ${pipVersion} install MySQL-python
	$getPermission ${pipVersion} install gevent
	$getPermission ${pipVersion} install numpy
	$getPermission ${pipVersion} install pandas
	$getPermission ${pipVersion} install scipy
	$getPermission ${pipVersion} install sympy
	$getPermission ${pipVersion} install statsmodels
	$getPermission ${pipVersion} install nltk
	$getPermission ${pipVersion} install time
	$getPermission ${pipVersion} install random
	$getPermission ${pipVersion} install sys
	$getPermission ${pipVersion} install xml
	$getPermission ${pipVersion} install pyyam
	$getPermission ${pipVersion} install configparser
	$getPermission ${pipVersion} install hashlib
	$getPermission ${pipVersion} install re
	$getPermission ${pipVersion} install itertools
	$getPermission ${pipVersion} install pdb
	$getPermission ${pipVersion} install traceback
	$getPermission ${pipVersion} install pprint
	$getPermission ${pipVersion} install logging
	$getPermission ${pipVersion} install urllib
	$getPermission ${pipVersion} install urllib2
	$getPermission ${pipVersion} install httplib
	$getPermission ${pipVersion} install pickle
	$getPermission ${pipVersion} install cpickle
	$getPermission ${pipVersion} install md5
	$getPermission ${pipVersion} install sha
	$getPermission ${pipVersion} install json
	$getPermission ${pipVersion} install simplejson
	$getPermission ${pipVersion} install timeit
	$getPermission ${pipVersion} install cprofile
	$getPermission ${pipVersion} install glob
	$getPermission ${pipVersion} install atexit
	$getPermission ${pipVersion} install dis
	$getPermission ${pipVersion} install paramiko
	$getPermission ${pipVersion} install selenium
	$getPermission ${pipVersion} install lxml
	$getPermission ${pipVersion} install mechanize
	$getPermission ${pipVersion} install pycurl
	$getPermission ${pipVersion} install fabric
	$getPermission ${pipVersion} install xmltodict
	$getPermission ${pipVersion} install urllib3
	$getPermission ${pipVersion} install flask
	$getPermission ${pipVersion} install ipdb
	$getPermission ${pipVersion} install redis
	$getPermission ${pipVersion} install mako
	$getPermission ${pipVersion} install pil
	$getPermission ${pipVersion} install matplotlib
	$getPermission ${pipVersion} install scrapy
	$getPermission ${pipVersion} install django
	$getPermission ${pipVersion} install tornado
	$getPermission ${pipVersion} install sh
	$getPermission ${pipVersion} install suds
	$getPermission ${pipVersion} install seaborn
	$getPermission ${pipVersion} install plotly
	$getPermission ${pipVersion} install bokeh
	$getPermission ${pipVersion} install pydot
	$getPermission ${pipVersion} install scikit-learn
	$getPermission ${pipVersion} install xgboost
	$getPermission ${pipVersion} install lightgbm
	$getPermission ${pipVersion} install catboost
	$getPermission ${pipVersion} install eli5
	$getPermission ${pipVersion} install tensorflow
	$getPermission ${pipVersion} install pytorch
	$getPermission ${pipVersion} install keras
	$getPermission ${pipVersion} install dist-keras
	$getPermission ${pipVersion} install elephas
	$getPermission ${pipVersion} install spark-deep-learning
	$getPermission ${pipVersion} install spacy
	$getPermission ${pipVersion} install gensim
	$getPermission ${pipVersion} install wxpython
	$getPermission ${pipVersion} install pillow
	$getPermission ${pipVersion} install sqlalchemy
	$getPermission ${pipVersion} install beautifulsoup
	$getPermission ${pipVersion} install twisted
	$getPermission ${pipVersion} install pygame
	$getPermission ${pipVersion} install pyglet
	$getPermission ${pipVersion} install pyqt
	$getPermission ${pipVersion} install pygtk
	$getPermission ${pipVersion} install scapy
	$getPermission ${pipVersion} install pywin32
	$getPermission ${pipVersion} install nose
	$getPermission ${pipVersion} install ipython
	$getPermission ${pipVersion} install math
	$getPermission ${pipVersion} install datetime
	$getPermission ${pipVersion} install psutil
	$getPermission ${pipVersion} install dnspython
	$getPermission ${pipVersion} install difflib
	$getPermission ${pipVersion} install filecmp
	$getPermission ${pipVersion} install smtplib
	$getPermission ${pipVersion} install xlsxwriter
	$getPermission ${pipVersion} install rrdtool
	$getPermission ${pipVersion} install pyclamad
	$getPermission ${pipVersion} install pexpect
	$getPermission ${pipVersion} install ggihttprequesthandler
	$getPermission ${pipVersion} install ansible
	$getPermission ${pipVersion} install yaml
	$getPermission ${pipVersion} install playbook
	$getPermission ${pipVersion} install saltstack
	$getPermission ${pipVersion} install func
	$getPermission ${pipVersion} install builtin
	$getPermission ${pipVersion} install exceptions
	$getPermission ${pipVersion} install stat
	$getPermission ${pipVersion} install string
	$getPermission ${pipVersion} install cmath
	$getPermission ${pipVersion} install operator
	$getPermission ${pipVersion} install copy
	$getPermission ${pipVersion} install types
	$getPermission ${pipVersion} install gc
	$getPermission ${pipVersion} install fileinput
	$getPermission ${pipVersion} install tempfile
	$getPermission ${pipVersion} install stringio
	$getPermission ${pipVersion} install cstringio
	$getPermission ${pipVersion} install mmap
	$getPermission ${pipVersion} install userdict
	$getPermission ${pipVersion} install userlist
	$getPermission ${pipVersion} install errno
	$getPermission ${pipVersion} install getopt
	$getPermission ${pipVersion} install getpass
	$getPermission ${pipVersion} install fnmatch
	$getPermission ${pipVersion} install whrandom
	$getPermission ${pipVersion} install cryopt
	$getPermission ${pipVersion} install rotor
	$getPermission ${pipVersion} install zlib
	$getPermission ${pipVersion} install code
	$getPermission ${pipVersion} install thread
	$getPermission ${pipVersion} install commands
	$getPermission ${pipVersion} install pipes
	$getPermission ${pipVersion} install popen2
	$getPermission ${pipVersion} install signal
	$getPermission ${pipVersion} install array
	$getPermission ${pipVersion} install struct
	$getPermission ${pipVersion} install sdrlib
	$getPermission ${pipVersion} install mashal
	$getPermission ${pipVersion} install copy_reg
	$getPermission ${pipVersion} install repr
	$getPermission ${pipVersion} install base64
	$getPermission ${pipVersion} install binhex
	$getPermission ${pipVersion} install quopri
	$getPermission ${pipVersion} install uu
	$getPermission ${pipVersion} install binascii
	$getPermission ${pipVersion} install xml.parsers.expat
	$getPermission ${pipVersion} install sgmllib
	$getPermission ${pipVersion} install htmllib
	$getPermission ${pipVersion} install htmlentitydefs
	$getPermission ${pipVersion} install dormatter
	$getPermission ${pipVersion} install netrc
	$getPermission ${pipVersion} install shlex
	$getPermission ${pipVersion} install zipfile
	$getPermission ${pipVersion} install gzip
	$getPermission ${pipVersion} install rfc822
	$getPermission ${pipVersion} install mimetools
	$getPermission ${pipVersion} install mimewriter
	$getPermission ${pipVersion} install mailbox
	$getPermission ${pipVersion} install mailcap
	$getPermission ${pipVersion} install mimetypes
	$getPermission ${pipVersion} install packmail
	$getPermission ${pipVersion} install mimify
	$getPermission ${pipVersion} install multifile
	$getPermission ${pipVersion} install socket
	$getPermission ${pipVersion} install select
	$getPermission ${pipVersion} install asyncore
	$getPermission ${pipVersion} install asynchat
	$getPermission ${pipVersion} install cookie
	$getPermission ${pipVersion} install robotparser
	$getPermission ${pipVersion} install ftplib
	$getPermission ${pipVersion} install gopherlib
	$getPermission ${pipVersion} install poplib
	$getPermission ${pipVersion} install imaplib
	$getPermission ${pipVersion} install telnetlib
	$getPermission ${pipVersion} install nntplib
	$getPermission ${pipVersion} install socketserver
	$getPermission ${pipVersion} install basehttpserver
	$getPermission ${pipVersion} install cgihttpserver
	$getPermission ${pipVersion} install cgi
	$getPermission ${pipVersion} install webbrowser
	$getPermission ${pipVersion} install locale
	$getPermission ${pipVersion} install unicodedata
	$getPermission ${pipVersion} install ucnhash
	$getPermission ${pipVersion} install imghdr
	$getPermission ${pipVersion} install sndhdr
	$getPermission ${pipVersion} install whatsound
	$getPermission ${pipVersion} install aifc
	$getPermission ${pipVersion} install sunau
	$getPermission ${pipVersion} install sunaudio
	$getPermission ${pipVersion} install wave
	$getPermission ${pipVersion} install audiodev
	$getPermission ${pipVersion} install winsound
	$getPermission ${pipVersion} install anydbm
	$getPermission ${pipVersion} install whichdb
	$getPermission ${pipVersion} install shelve
	$getPermission ${pipVersion} install dbhash
	$getPermission ${pipVersion} install dbm
	$getPermission ${pipVersion} install dumbdbm
	$getPermission ${pipVersion} install gdbm
	$getPermission ${pipVersion} install bdb
	$getPermission ${pipVersion} install profile
	$getPermission ${pipVersion} install pstats
	$getPermission ${pipVersion} install tabnanny
	$getPermission ${pipVersion} install fcntl
	$getPermission ${pipVersion} install pwd
	$getPermission ${pipVersion} install grp
	$getPermission ${pipVersion} install nix
	$getPermission ${pipVersion} install curses
	$getPermission ${pipVersion} install termios
	$getPermission ${pipVersion} install tty
	$getPermission ${pipVersion} install resource
	$getPermission ${pipVersion} install syslog
	$getPermission ${pipVersion} install msvcrt
	$getPermission ${pipVersion} install nt
	$getPermission ${pipVersion} install _winreg
	$getPermission ${pipVersion} install winreg
	$getPermission ${pipVersion} install winreg
	$getPermission ${pipVersion} install posix
	$getPermission ${pipVersion} install dospath
	$getPermission ${pipVersion} install macpath
	$getPermission ${pipVersion} install ntpath
	$getPermission ${pipVersion} install posixpath
	$getPermission ${pipVersion} install strop
	$getPermission ${pipVersion} install imp
	$getPermission ${pipVersion} install new
	$getPermission ${pipVersion} install pre
	$getPermission ${pipVersion} install sre
	$getPermission ${pipVersion} install py_compile
	$getPermission ${pipVersion} install compileall
	$getPermission ${pipVersion} install ihooks
	$getPermission ${pipVersion} install linecache
	$getPermission ${pipVersion} install macurl2path
	$getPermission ${pipVersion} install tokenize
	$getPermission ${pipVersion} install keyword
	$getPermission ${pipVersion} install symbol
	$getPermission ${pipVersion} install token
	$getPermission ${pipVersion} install pyclbr
	$getPermission ${pipVersion} install cmd
	$getPermission ${pipVersion} install rexec
	$getPermission ${pipVersion} install bastion
	$getPermission ${pipVersion} install Bastion
	$getPermission ${pipVersion} install readline
	$getPermission ${pipVersion} install rlcompleter
	$getPermission ${pipVersion} install statvfs
	$getPermission ${pipVersion} install calendar
	$getPermission ${pipVersion} install sched
	$getPermission ${pipVersion} install statcache
	$getPermission ${pipVersion} install grep
	$getPermission ${pipVersion} install dircache
	$getPermission ${pipVersion} install dircmp
	$getPermission ${pipVersion} install cmp
	$getPermission ${pipVersion} install cmpcache
	$getPermission ${pipVersion} install util
	$getPermission ${pipVersion} install soundex
	$getPermission ${pipVersion} install timing
	$getPermission ${pipVersion} install posixfile
	$getPermission ${pipVersion} install bisect
	$getPermission ${pipVersion} install knee
	$getPermission ${pipVersion} install tzparse
	$getPermission ${pipVersion} install regex
	$getPermission ${pipVersion} install regsub
	$getPermission ${pipVersion} install reconvert
	$getPermission ${pipVersion} install regex_syntax
	$getPermission ${pipVersion} install find
	$getPermission ${pipVersion} install textwrap
	$getPermission ${pipVersion} install stringprep
	$getPermission ${pipVersion} install codecs
	$getPermission ${pipVersion} install collections.abc
	$getPermission ${pipVersion} install heapq
	$getPermission ${pipVersion} install weakref
	$getPermission ${pipVersion} install reprlib
	$getPermission ${pipVersion} install numbers
	$getPermission ${pipVersion} install fractions
	$getPermission ${pipVersion} install decimal
	$getPermission ${pipVersion} install stat
	$getPermission ${pipVersion} install copyreg
	$getPermission ${pipVersion} install marshal
	$getPermission ${pipVersion} install sqlite3
	$getPermission ${pipVersion} install zlib
	$getPermission ${pipVersion} install bz2
	$getPermission ${pipVersion} install lzma
	$getPermission ${pipVersion} install tarfile
	$getPermission ${pipVersion} install xdrlib
	$getPermission ${pipVersion} install plistlib
	$getPermission ${pipVersion} install hmac
	$getPermission ${pipVersion} install optparser
	$getPermission ${pipVersion} install platform
	$getPermission ${pipVersion} install ctypes
	$getPermission ${pipVersion} install concurrent
	$getPermission ${pipVersion} install dummy_threading
	$getPermission ${pipVersion} install _thread
	$getPermission ${pipVersion} install _dummy_thread
	$getPermission ${pipVersion} install ssl
	$getPermission ${pipVersion} install email
	$getPermission ${pipVersion} install html
	$getPermission ${pipVersion} install wsgiref
	$getPermission ${pipVersion} install http
	$getPermission ${pipVersion} install smtpd
	$getPermission ${pipVersion} install uuid
	$getPermission ${pipVersion} install xmlrpc
	$getPermission ${pipVersion} install ipaddress
	$getPermission ${pipVersion} install audioop
	$getPermission ${pipVersion} install chunk
	$getPermission ${pipVersion} install colorsys
	$getPermission ${pipVersion} install ossaudiodev
	$getPermission ${pipVersion} install gettext
	$getPermission ${pipVersion} install turtle
	$getPermission ${pipVersion} install tkinter
	$getPermission ${pipVersion} install tkinter.ttk
	$getPermission ${pipVersion} install pydoc
	$getPermission ${pipVersion} install doctest
	$getPermission ${pipVersion} install unittest
	$getPermission ${pipVersion} install test
	$getPermission ${pipVersion} install venv
	$getPermission ${pipVersion} install faulthandler
	$getPermission ${pipVersion} install trace
	$getPermission ${pipVersion} install sysconfig
	$getPermission ${pipVersion} install main
	$getPermission ${pipVersion} install warnings
	$getPermission ${pipVersion} install contextlib
	$getPermission ${pipVersion} install abc
	$getPermission ${pipVersion} install atexit
	$getPermission ${pipVersion} install future
	$getPermission ${pipVersion} install inspect
	$getPermission ${pipVersion} install site
	$getPermission ${pipVersion} install fpectl
	$getPermission ${pipVersion} install distutils
	$getPermission ${pipVersion} install codeop
	$getPermission ${pipVersion} install zipimport
	$getPermission ${pipVersion} install pkgutil
	$getPermission ${pipVersion} install modulefinder
	$getPermission ${pipVersion} install runpy
	$getPermission ${pipVersion} install importlib
	$getPermission ${pipVersion} install ast
	$getPermission ${pipVersion} install symtable
	$getPermission ${pipVersion} install tabnany
	$getPermission ${pipVersion} install formatter
	$getPermission ${pipVersion} install msilib
	$getPermission ${pipVersion} install spwd
	$getPermission ${pipVersion} install crypt
	$getPermission ${pipVersion} install pty
	$getPermission ${pipVersion} install nis
	$getPermission ${pipVersion} install opencv-python
	$getPermission ${pipVersion} install mysql-python
	$getPermission ${pipVersion} install agate
	$getPermission ${pipVersion} install agate-dbf
	$getPermission ${pipVersion} install agate-excel
	$getPermission ${pipVersion} install agate-sql
	$getPermission ${pipVersion} install Babel
	$getPermission ${pipVersion} install csvkit
	$getPermission ${pipVersion} install dbfread
	$getPermission ${pipVersion} install et-xmlfile
	$getPermission ${pipVersion} install isodate
	$getPermission ${pipVersion} install jdcal
	$getPermission ${pipVersion} install leather
	$getPermission ${pipVersion} install openpyxl
	$getPermission ${pipVersion} install parsedatetime
	$getPermission ${pipVersion} install python-slugify
	$getPermission ${pipVersion} install pytimeparse
	$getPermission ${pipVersion} install pytz
	$getPermission ${pipVersion} install six
	$getPermission ${pipVersion} install SQLAlchemy
	$getPermission ${pipVersion} install text-unidecode
	$getPermission ${pipVersion} install xlrd
	$getPermission ${pipVersion} install -lxc
	$getPermission ${pipVersion} install lxc
	$getPermission ${pipVersion} install cached-property
	$getPermission ${pipVersion} install chardet
	$getPermission ${pipVersion} install docker
	$getPermission ${pipVersion} install docker-compose
	$getPermission ${pipVersion} install docker-pycreds
	$getPermission ${pipVersion} install dockerpty
	$getPermission ${pipVersion} install docopt
	$getPermission ${pipVersion} install httplib2
	$getPermission ${pipVersion} install idna
	$getPermission ${pipVersion} install jsonschema
	$getPermission ${pipVersion} install NetEase-MusicBox
	$getPermission ${pipVersion} install openshot-qt
	$getPermission ${pipVersion} install pip
	$getPermission ${pipVersion} install pycryptodomex
	$getPermission ${pipVersion} install PyQt5
	$getPermission ${pipVersion} install PyQt5-sip
	$getPermission ${pipVersion} install PySocks
	$getPermission ${pipVersion} install PyYAML
	$getPermission ${pipVersion} install pyzmq
	$getPermission ${pipVersion} install requests-cache
	$getPermission ${pipVersion} install setuptools
	$getPermission ${pipVersion} install six
	$getPermission ${pipVersion} install texttable
	$getPermission ${pipVersion} install websocket-client
	$getPermission ${pipVersion} install wheel
	$getPermission ${pipVersion} install slsx2csv
	$getPermission ${pipVersion} install networkx
	$getPermission ${pipVersion} install mgzip
	$getPermission ${pipVersion} install sklearn
	$getPermission ${pipVersion} install guppy


	#The following modules come from [https://www.lfd.uci.edu/~gohlke/pythonlibs/] , are some useful Python modules.
	$getPermission ${pipVersion} install pygit2
	$getPermission ${pipVersion} install tifffile
	$getPermission ${pipVersion} install logbook
	$getPermission ${pipVersion} install py-lmdb
	$getPermission ${pipVersion} install sounddevice
	$getPermission ${pipVersion} install blosc
	$getPermission ${pipVersion} install pyfmi
	$getPermission ${pipVersion} install cairocffi
	$getPermission ${pipVersion} install scikit-umfpack
	$getPermission ${pipVersion} install pystemmer
	$getPermission ${pipVersion} install pyusb-ftdi
	$getPermission ${pipVersion} install fisher
	$getPermission ${pipVersion} install liblinear
	$getPermission ${pipVersion} install arctic
	$getPermission ${pipVersion} install enable
	$getPermission ${pipVersion} install fabio
	$getPermission ${pipVersion} install bcolz
	$getPermission ${pipVersion} install kapteyn
	$getPermission ${pipVersion} install pyksvd
	$getPermission ${pipVersion} install psycopg
	$getPermission ${pipVersion} install lfdfiles
	$getPermission ${pipVersion} install ets
	$getPermission ${pipVersion} install zfec
	$getPermission ${pipVersion} install pyswisseph
	$getPermission ${pipVersion} install pyyaml
	$getPermission ${pipVersion} install mmtk
	$getPermission ${pipVersion} install scikit-misc
	$getPermission ${pipVersion} install greenlet
	$getPermission ${pipVersion} install pybluez
	$getPermission ${pipVersion} install python-sundials
	$getPermission ${pipVersion} install pyjnius
	$getPermission ${pipVersion} install yappi
	$getPermission ${pipVersion} install pyproj
	$getPermission ${pipVersion} install pyamg
	$getPermission ${pipVersion} install glfw
	$getPermission ${pipVersion} install opencv
	$getPermission ${pipVersion} install cupy
	$getPermission ${pipVersion} install spglib
	$getPermission ${pipVersion} install netcdf4
	$getPermission ${pipVersion} install milk
	$getPermission ${pipVersion} install libxml-python
	$getPermission ${pipVersion} install pystackreg
	$getPermission ${pipVersion} install pycosat
	$getPermission ${pipVersion} install steps
	$getPermission ${pipVersion} install noise
	$getPermission ${pipVersion} install minepy
	$getPermission ${pipVersion} install nlopt
	$getPermission ${pipVersion} install bazaar
	$getPermission ${pipVersion} install seqlearn
	$getPermission ${pipVersion} install scikits.samplerate
	$getPermission ${pipVersion} install jcc
	$getPermission ${pipVersion} install cython
	$getPermission ${pipVersion} install polygon
	$getPermission ${pipVersion} install postgresadapter
	$getPermission ${pipVersion} install pybox2d
	$getPermission ${pipVersion} install babel
	$getPermission ${pipVersion} install rpy2
	$getPermission ${pipVersion} install simpleitk
	$getPermission ${pipVersion} install cantera
	$getPermission ${pipVersion} install cgal-bindings
	$getPermission ${pipVersion} install dubins
	$getPermission ${pipVersion} install wrapt
	$getPermission ${pipVersion} install pydantic
	$getPermission ${pipVersion} install llist
	$getPermission ${pipVersion} install meshpy
	$getPermission ${pipVersion} install line_profiler
	$getPermission ${pipVersion} install delny
	$getPermission ${pipVersion} install iocbio
	$getPermission ${pipVersion} install traits
	$getPermission ${pipVersion} install kiwisolver
	$getPermission ${pipVersion} install liblas
	$getPermission ${pipVersion} install pyldap
	$getPermission ${pipVersion} install bitarray
	$getPermission ${pipVersion} install nitime
	$getPermission ${pipVersion} install persistent
	$getPermission ${pipVersion} install qutip
	$getPermission ${pipVersion} install sparsesvd
	$getPermission ${pipVersion} install open3d
	$getPermission ${pipVersion} install ta-lib
	$getPermission ${pipVersion} install pulp
	$getPermission ${pipVersion} install pydde
	$getPermission ${pipVersion} install msgpack
	$getPermission ${pipVersion} install cyassimp
	$getPermission ${pipVersion} install pyminuit
	$getPermission ${pipVersion} install ujson
	$getPermission ${pipVersion} install pypmc
	$getPermission ${pipVersion} install qimage2ndarray
	$getPermission ${pipVersion} install pendulum
	$getPermission ${pipVersion} install numpy-quaternion
	$getPermission ${pipVersion} install louvain-igraph
	$getPermission ${pipVersion} install hdf5plugin
	$getPermission ${pipVersion} install python-ldap
	$getPermission ${pipVersion} install centrosome
	$getPermission ${pipVersion} install pyhull
	$getPermission ${pipVersion} install h5py
	$getPermission ${pipVersion} install lazyflow
	$getPermission ${pipVersion} install btrees
	$getPermission ${pipVersion} install sdtfile
	$getPermission ${pipVersion} install pycvodes
	$getPermission ${pipVersion} install pygraphviz
	$getPermission ${pipVersion} install imreg
	$getPermission ${pipVersion} install mercurial
	$getPermission ${pipVersion} install cytoolz
	$getPermission ${pipVersion} install mpi4py
	$getPermission ${pipVersion} install scikits.ann
	$getPermission ${pipVersion} install bigfloat
	$getPermission ${pipVersion} install pyephem
	$getPermission ${pipVersion} install scikits.vectorplot
	$getPermission ${pipVersion} install pycorrfit
	$getPermission ${pipVersion} install pyxml
	$getPermission ${pipVersion} install videocapture
	$getPermission ${pipVersion} install hdbscan
	$getPermission ${pipVersion} install gvar
	$getPermission ${pipVersion} install fonttools
	$getPermission ${pipVersion} install pycogent
	$getPermission ${pipVersion} install lucam
	$getPermission ${pipVersion} install mlpy
	$getPermission ${pipVersion} install setproctitle
	$getPermission ${pipVersion} install pymca
	$getPermission ${pipVersion} install tatsu
	$getPermission ${pipVersion} install mysqlclient
	$getPermission ${pipVersion} install javabridge
	$getPermission ${pipVersion} install iris
	$getPermission ${pipVersion} install cgohlke
	$getPermission ${pipVersion} install pyzopfli
	$getPermission ${pipVersion} install grako
	$getPermission ${pipVersion} install pyrsistent
	$getPermission ${pipVersion} install x86cpu
	$getPermission ${pipVersion} install lazy_object_proxy
	$getPermission ${pipVersion} install pymcmc
	$getPermission ${pipVersion} install wordcloud
	$getPermission ${pipVersion} install ahds
	$getPermission ${pipVersion} install cgkit
	$getPermission ${pipVersion} install pyslalib
	$getPermission ${pipVersion} install numexpr
	$getPermission ${pipVersion} install atom
	$getPermission ${pipVersion} install blz
	$getPermission ${pipVersion} install zstd
	$getPermission ${pipVersion} install czifile
	$getPermission ${pipVersion} install scikits.scattpy
	$getPermission ${pipVersion} install pyclearvolume
	$getPermission ${pipVersion} install thriftpy
	$getPermission ${pipVersion} install friture
	$getPermission ${pipVersion} install pycares
	$getPermission ${pipVersion} install pocketsphinx
	$getPermission ${pipVersion} install pymc
	$getPermission ${pipVersion} install pyopengl
	$getPermission ${pipVersion} install zope.interface
	$getPermission ${pipVersion} install gitdb
	$getPermission ${pipVersion} install casuarius
	$getPermission ${pipVersion} install mkl_random
	$getPermission ${pipVersion} install quantlib
	$getPermission ${pipVersion} install basemap
	$getPermission ${pipVersion} install cf-units
	$getPermission ${pipVersion} install gr
	$getPermission ${pipVersion} install cmapfile
	$getPermission ${pipVersion} install pylvgl
	$getPermission ${pipVersion} install fpzip
	$getPermission ${pipVersion} install mayavi
	$getPermission ${pipVersion} install ndimage
	$getPermission ${pipVersion} install pyhdf
	$getPermission ${pipVersion} install mod_wsgi
	$getPermission ${pipVersion} install natgrid
	$getPermission ${pipVersion} install scikit-fmm
	$getPermission ${pipVersion} install pyasn
	$getPermission ${pipVersion} install vispy
	$getPermission ${pipVersion} install brotlipy
	$getPermission ${pipVersion} install py_gd
	$getPermission ${pipVersion} install mxbase
	$getPermission ${pipVersion} install libsbml
	$getPermission ${pipVersion} install nmoldyn
	$getPermission ${pipVersion} install simpleaudio
	$getPermission ${pipVersion} install pygresql
	$getPermission ${pipVersion} install polylearn
	$getPermission ${pipVersion} install typed_ast
	$getPermission ${pipVersion} install gmpy
	$getPermission ${pipVersion} install grpcio
	$getPermission ${pipVersion} install pycairo
	$getPermission ${pipVersion} install recordclass
	$getPermission ${pipVersion} install yarl
	$getPermission ${pipVersion} install pyqwt
	$getPermission ${pipVersion} install aiohttp
	$getPermission ${pipVersion} install dipy
	$getPermission ${pipVersion} install pyisapie
	$getPermission ${pipVersion} install wrf_python
	$getPermission ${pipVersion} install pyside
	$getPermission ${pipVersion} install pydbg
	$getPermission ${pipVersion} install pysfml
	$getPermission ${pipVersion} install winrandom
	$getPermission ${pipVersion} install blaze
	$getPermission ${pipVersion} install astropy
	$getPermission ${pipVersion} install scimath
	$getPermission ${pipVersion} install cellcognition
	$getPermission ${pipVersion} install mkl-service
	$getPermission ${pipVersion} install pywavelets
	$getPermission ${pipVersion} install zipline
	$getPermission ${pipVersion} install pyropes
	$getPermission ${pipVersion} install pywcs
	$getPermission ${pipVersion} install osqp
	$getPermission ${pipVersion} install pillow-simd
	$getPermission ${pipVersion} install fasttext
	$getPermission ${pipVersion} install pylibjpeg
	$getPermission ${pipVersion} install celiagg
	$getPermission ${pipVersion} install pytiff
	$getPermission ${pipVersion} install roifile
	$getPermission ${pipVersion} install pyfltk
	$getPermission ${pipVersion} install pymedia
	$getPermission ${pipVersion} install bintrees
	$getPermission ${pipVersion} install cheetah
	$getPermission ${pipVersion} install entropy
	$getPermission ${pipVersion} install ode
	$getPermission ${pipVersion} install python-igraph
	$getPermission ${pipVersion} install imread
	$getPermission ${pipVersion} install carray
	$getPermission ${pipVersion} install scikits.odes
	$getPermission ${pipVersion} install sima
	$getPermission ${pipVersion} install pyx
	$getPermission ${pipVersion} install cyrasterize
	$getPermission ${pipVersion} install cx_oracle
	$getPermission ${pipVersion} install aggdraw
	$getPermission ${pipVersion} install msvc_runtime
	$getPermission ${pipVersion} install multiprocess
	$getPermission ${pipVersion} install blis
	$getPermission ${pipVersion} install llvmlite
	$getPermission ${pipVersion} install pymcubes
	$getPermission ${pipVersion} install markupsafe
	$getPermission ${pipVersion} install datrie
	$getPermission ${pipVersion} install partseg
	$getPermission ${pipVersion} install lsqfit
	$getPermission ${pipVersion} install cvxopt
	$getPermission ${pipVersion} install scientificpython
	$getPermission ${pipVersion} install py-earth
	$getPermission ${pipVersion} install vigra
	$getPermission ${pipVersion} install rtree
	$getPermission ${pipVersion} install leidenalg
	$getPermission ${pipVersion} install bitshuffle
	$getPermission ${pipVersion} install scikit-image
	$getPermission ${pipVersion} install cx_freeze
	$getPermission ${pipVersion} install zodbpickle
	$getPermission ${pipVersion} install reportlab
	$getPermission ${pipVersion} install pytst
	$getPermission ${pipVersion} install ffnet
	$getPermission ${pipVersion} install multineat
	$getPermission ${pipVersion} install pyexiv2
	$getPermission ${pipVersion} install fastcluster
	$getPermission ${pipVersion} install imagecodecs-lite
	$getPermission ${pipVersion} install twainmodule
	$getPermission ${pipVersion} install openpiv
	$getPermission ${pipVersion} install pyfm
	$getPermission ${pipVersion} install marisa-trie
	$getPermission ${pipVersion} install pymunk
	$getPermission ${pipVersion} install tinyarray
	$getPermission ${pipVersion} install hmmlearn
	$getPermission ${pipVersion} install glumpy
	$getPermission ${pipVersion} install freetypepy
	$getPermission ${pipVersion} install pgmagick
	$getPermission ${pipVersion} install heatmap
	$getPermission ${pipVersion} install numba
	$getPermission ${pipVersion} install rapidjson
	$getPermission ${pipVersion} install indexed_gzip
	$getPermission ${pipVersion} install cld
	$getPermission ${pipVersion} install veusz
	$getPermission ${pipVersion} install scs
	$getPermission ${pipVersion} install pyviennacl
	$getPermission ${pipVersion} install lz4
	$getPermission ${pipVersion} install pyqt4
	$getPermission ${pipVersion} install lightning
	$getPermission ${pipVersion} install bio_formats
	$getPermission ${pipVersion} install pymssql
	$getPermission ${pipVersion} install pyarrow
	$getPermission ${pipVersion} install chebyfit
	$getPermission ${pipVersion} install oursql
	$getPermission ${pipVersion} install pysparse
	$getPermission ${pipVersion} install assimulo
	$getPermission ${pipVersion} install python-lzo
	$getPermission ${pipVersion} install fann2
	$getPermission ${pipVersion} install flann
	$getPermission ${pipVersion} install multidict
	$getPermission ${pipVersion} install thrift
	$getPermission ${pipVersion} install pymaxflow
	$getPermission ${pipVersion} install hyperspy
	$getPermission ${pipVersion} install llvmpy
	$getPermission ${pipVersion} install cobra
	$getPermission ${pipVersion} install shapely
	$getPermission ${pipVersion} install icsdll
	$getPermission ${pipVersion} install imagecodecs
	$getPermission ${pipVersion} install molmass
	$getPermission ${pipVersion} install scikits.hydroclimpy
	$getPermission ${pipVersion} install debug-information-files
	$getPermission ${pipVersion} install moderngl
	$getPermission ${pipVersion} install qt_graph_helpers
	$getPermission ${pipVersion} install sfepy
	$getPermission ${pipVersion} install quickfix
	$getPermission ${pipVersion} install boost.python
	$getPermission ${pipVersion} install opentsne
	$getPermission ${pipVersion} install protobuf
	$getPermission ${pipVersion} install cftime
	$getPermission ${pipVersion} install backports.lzma
	$getPermission ${pipVersion} install vtk
	$getPermission ${pipVersion} install imaged11
	$getPermission ${pipVersion} install intbitset
	$getPermission ${pipVersion} install scikit-cycling
	$getPermission ${pipVersion} install fastrlock
	$getPermission ${pipVersion} install fmkr
	$getPermission ${pipVersion} install pyicu
	$getPermission ${pipVersion} install apsw
	$getPermission ${pipVersion} install iminuit
	$getPermission ${pipVersion} install xxhash
	$getPermission ${pipVersion} install simpleparse
	$getPermission ${pipVersion} install pytables
	$getPermission ${pipVersion} install python-cjson
	$getPermission ${pipVersion} install pyemd
	$getPermission ${pipVersion} install zopflipy
	$getPermission ${pipVersion} install rasterio
	$getPermission ${pipVersion} install scandir
	$getPermission ${pipVersion} install pythonnet
	$getPermission ${pipVersion} install htseq
	$getPermission ${pipVersion} install bottleneck
	$getPermission ${pipVersion} install jpype
	$getPermission ${pipVersion} install openbabel
	$getPermission ${pipVersion} install pyaudio
	$getPermission ${pipVersion} install pymix
	$getPermission ${pipVersion} install elasticdeform
	$getPermission ${pipVersion} install vidsrc
	$getPermission ${pipVersion} install scikits.timeseries
	$getPermission ${pipVersion} install pylibtiff
	$getPermission ${pipVersion} install ceodbc
	$getPermission ${pipVersion} install bsdiff4
	$getPermission ${pipVersion} install kwant
	$getPermission ${pipVersion} install python-snappy
	$getPermission ${pipVersion} install re2
	$getPermission ${pipVersion} install mmlib
	$getPermission ${pipVersion} install pylibdeconv
	$getPermission ${pipVersion} install cmarkgfm
	$getPermission ${pipVersion} install polymode
	$getPermission ${pipVersion} install crcmod
	$getPermission ${pipVersion} install planar
	$getPermission ${pipVersion} install cffi
	$getPermission ${pipVersion} install pyodbc
	$getPermission ${pipVersion} install py2exe
	$getPermission ${pipVersion} install sendkeys
	$getPermission ${pipVersion} install genshi
	$getPermission ${pipVersion} install transformations
	$getPermission ${pipVersion} install mistune
	$getPermission ${pipVersion} install discretize
	$getPermission ${pipVersion} install google-crc32c
	$getPermission ${pipVersion} install obspy
	$getPermission ${pipVersion} install salientdetect
	$getPermission ${pipVersion} install fisx
	$getPermission ${pipVersion} install orange
	$getPermission ${pipVersion} install mkl_fft
	$getPermission ${pipVersion} install pyopencl
	$getPermission ${pipVersion} install tiledb
	$getPermission ${pipVersion} install python-levenshtein
	$getPermission ${pipVersion} install silvercity
	$getPermission ${pipVersion} install fiona
	$getPermission ${pipVersion} install zfpy
	$getPermission ${pipVersion} install la
	$getPermission ${pipVersion} install libpython
	$getPermission ${pipVersion} install yt
	$getPermission ${pipVersion} install pymetis
	$getPermission ${pipVersion} install ruamel.yaml
	$getPermission ${pipVersion} install pyeda
	$getPermission ${pipVersion} install pyfits
	$getPermission ${pipVersion} install umysql
	$getPermission ${pipVersion} install chaco
	$getPermission ${pipVersion} install dynd
	$getPermission ${pipVersion} install pycuda
	$getPermission ${pipVersion} install trollius
	$getPermission ${pipVersion} install pyqpbo
	$getPermission ${pipVersion} install pyvrml97
	$getPermission ${pipVersion} install pylzma
	$getPermission ${pipVersion} install python-geohash
	$getPermission ${pipVersion} install ilastik
	$getPermission ${pipVersion} install bsddb3
	$getPermission ${pipVersion} install fastparquet
	$getPermission ${pipVersion} install fast-histogram
	$getPermission ${pipVersion} install pyrxp
	$getPermission ${pipVersion} install qdafile
	$getPermission ${pipVersion} install fcsfiles
	$getPermission ${pipVersion} install blist
	$getPermission ${pipVersion} install naturalneighbor
	$getPermission ${pipVersion} install slycot
	$getPermission ${pipVersion} install enaml
	$getPermission ${pipVersion} install coverage
	$getPermission ${pipVersion} install boost-histogram
	$getPermission ${pipVersion} install mplcairo
	$getPermission ${pipVersion} install nipy
	$getPermission ${pipVersion} install pycld2
	$getPermission ${pipVersion} install hddm
	$getPermission ${pipVersion} install openexr
	$getPermission ${pipVersion} install pyflux
	$getPermission ${pipVersion} install libsvm
	$getPermission ${pipVersion} install libtfr
	$getPermission ${pipVersion} install pyalembic
	$getPermission ${pipVersion} install pyodeint
	$getPermission ${pipVersion} install dulwich
	$getPermission ${pipVersion} install autopy
	$getPermission ${pipVersion} install dnacurve
	$getPermission ${pipVersion} install gpy
	$getPermission ${pipVersion} install cartopy
	$getPermission ${pipVersion} install dukpy
	$getPermission ${pipVersion} install swiglpk
	$getPermission ${pipVersion} install numpy-stl
	$getPermission ${pipVersion} install pycluster
	$getPermission ${pipVersion} install pycryptosat
	$getPermission ${pipVersion} install stratify
	$getPermission ${pipVersion} install pythonmagick
	$getPermission ${pipVersion} install tomopy
	$getPermission ${pipVersion} install vpython
	$getPermission ${pipVersion} install freesasa
	$getPermission ${pipVersion} install gdal
	$getPermission ${pipVersion} install scikits.delaunay
	$getPermission ${pipVersion} install sasl
	$getPermission ${pipVersion} install psf
	$getPermission ${pipVersion} install cdecimal
	$getPermission ${pipVersion} install ecos
	$getPermission ${pipVersion} install cellprofiler
	$getPermission ${pipVersion} install cyordereddict
	$getPermission ${pipVersion} install chompack
	$getPermission ${pipVersion} install rtmidi-python
	$getPermission ${pipVersion} install python-lzf
	$getPermission ${pipVersion} install pyhook
	$getPermission ${pipVersion} install udunits
	$getPermission ${pipVersion} install pydensecrf
	$getPermission ${pipVersion} install pywinpty
	$getPermission ${pipVersion} install annoy
	$getPermission ${pipVersion} install pyamf
	$getPermission ${pipVersion} install uciwebauth
	$getPermission ${pipVersion} install aicspylibczi
	$getPermission ${pipVersion} install pylibczi
	$getPermission ${pipVersion} install mathutils
	$getPermission ${pipVersion} install xylib-py
	$getPermission ${pipVersion} install medussa
	$getPermission ${pipVersion} install scipy-cluster
	$getPermission ${pipVersion} install pymvpa
	$getPermission ${pipVersion} install brotli
	$getPermission ${pipVersion} install lru_dict
	$getPermission ${pipVersion} install pysqlite
	$getPermission ${pipVersion} install scikits.audiolab
	$getPermission ${pipVersion} install netifaces
	$getPermission ${pipVersion} install lp_solve
	$getPermission ${pipVersion} install mahotas
	$getPermission ${pipVersion} install triangle
	$getPermission ${pipVersion} install daal4py
	$getPermission ${pipVersion} install biopython
	$getPermission ${pipVersion} install guiqwt
	$getPermission ${pipVersion} install holopy
	$getPermission ${pipVersion} install pywinhook
	$getPermission ${pipVersion} install akima
	$getPermission ${pipVersion} install jsonobject
	$getPermission ${pipVersion} install dawg
	$getPermission ${pipVersion} install pystruct
	$getPermission ${pipVersion} install pycifrw
	$getPermission ${pipVersion} install oiffile
	$getPermission ${pipVersion} install mxnet
	$getPermission ${pipVersion} install spectrum
	$getPermission ${pipVersion} install pymutt
	$getPermission ${pipVersion} install zs
	$getPermission ${pipVersion} install pymol-open-source
	$getPermission ${pipVersion} install pymatgen
	$getPermission ${pipVersion} install crc16
	$getPermission ${pipVersion} install fastcache
	$getPermission ${pipVersion} install py-fcm
	$getPermission ${pipVersion} install numcodecs
	$getPermission ${pipVersion} install freeimagedll
	$getPermission ${pipVersion} install netpbmfile
	$getPermission ${pipVersion} install cvxpy
	$getPermission ${pipVersion} install kivy
	$getPermission ${pipVersion} install zeroc-ice
	$getPermission ${pipVersion} install aspell-python
	$getPermission ${pipVersion} install pykinsol
	$getPermission ${pipVersion} install jupyter
	$getPermission ${pipVersion} install cvxcanon
	$getPermission ${pipVersion} install menpo
	$getPermission ${pipVersion} install ad3
	$getPermission ${pipVersion} install cchardet
	$getPermission ${pipVersion} install openimageio
	$getPermission ${pipVersion} install pyspharm
	$getPermission ${pipVersion} install fdint
	$getPermission ${pipVersion} install jsonlib
	$getPermission ${pipVersion} install peewee
	$getPermission ${pipVersion} install pyfftw
	
	i=`expr $i + 1`
done
