#!/bin/bash

getPermission="sudo "
readonly getPermission

pipVersion=""

#logFile="pythonModulesBatchInstall-successful.log"
#readonly logFile

exec_Times=6
i=1

#touch $logFile

while [ $i -le ${exec_Times} ]
do
	if [[ $i -le 3 ]]
	then
		pipVersion="pip"
	else
		pipVersion="pip3"
	fi

	$getPermission pipVersion install cx_Oracle
	$getPermission pipVersion install filetype
	$getPermission pipVersion install memory_profiler
	$getPermission pipVersion install shutil
	$getPermission pipVersion install crontab
	$getPermission pipVersion install contextmanger
	$getPermission pipVersion install multiprocessing
	$getPermission pipVersion install bottle
	$getPermission pipVersion install argparse
	$getPermission pipVersion install collections
	$getPermission pipVersion install functools
	$getPermission pipVersion install glob
	$getPermission pipVersion install os
	$getPermission pipVersion install queue
	$getPermission pipVersion install simplehttpserver
	$getPermission pipVersion install subprocess
	$getPermission pipVersion install threading
	$getPermission pipVersion install requests
	$getPermission pipVersion install bs4
	$getPermission pipVersion install csv
	$getPermission pipVersion install pymongo
	$getPermission pipVersion install MySQL-python
	$getPermission pipVersion install gevent
	$getPermission pipVersion install numpy
	$getPermission pipVersion install pandas
	$getPermission pipVersion install scipy
	$getPermission pipVersion install sympy
	$getPermission pipVersion install statsmodels
	$getPermission pipVersion install nltk
	$getPermission pipVersion install time
	$getPermission pipVersion install random
	$getPermission pipVersion install sys
	$getPermission pipVersion install xml
	$getPermission pipVersion install pyyam
	$getPermission pipVersion install configparser
	$getPermission pipVersion install hashlib
	$getPermission pipVersion install re
	$getPermission pipVersion install itertools
	$getPermission pipVersion install pdb
	$getPermission pipVersion install traceback
	$getPermission pipVersion install pprint
	$getPermission pipVersion install logging
	$getPermission pipVersion install urllib
	$getPermission pipVersion install urllib2
	$getPermission pipVersion install httplib
	$getPermission pipVersion install pickle
	$getPermission pipVersion install cpickle
	$getPermission pipVersion install md5
	$getPermission pipVersion install sha
	$getPermission pipVersion install json
	$getPermission pipVersion install simplejson
	$getPermission pipVersion install timeit
	$getPermission pipVersion install cprofile
	$getPermission pipVersion install glob
	$getPermission pipVersion install atexit
	$getPermission pipVersion install dis
	$getPermission pipVersion install paramiko
	$getPermission pipVersion install selenium
	$getPermission pipVersion install lxml
	$getPermission pipVersion install mechanize
	$getPermission pipVersion install pycurl
	$getPermission pipVersion install fabric
	$getPermission pipVersion install xmltodict
	$getPermission pipVersion install urllib3
	$getPermission pipVersion install flask
	$getPermission pipVersion install ipdb
	$getPermission pipVersion install redis
	$getPermission pipVersion install mako
	$getPermission pipVersion install pil
	$getPermission pipVersion install matplotlib
	$getPermission pipVersion install scrapy
	$getPermission pipVersion install django
	$getPermission pipVersion install tornado
	$getPermission pipVersion install sh
	$getPermission pipVersion install suds
	$getPermission pipVersion install seaborn
	$getPermission pipVersion install plotly
	$getPermission pipVersion install bokeh
	$getPermission pipVersion install pydot
	$getPermission pipVersion install scikit-learn
	$getPermission pipVersion install xgboost
	$getPermission pipVersion install lightgbm
	$getPermission pipVersion install catboost
	$getPermission pipVersion install eli5
	$getPermission pipVersion install tensorflow
	$getPermission pipVersion install pytorch
	$getPermission pipVersion install keras
	$getPermission pipVersion install dist-keras
	$getPermission pipVersion install elephas
	$getPermission pipVersion install spark-deep-learning
	$getPermission pipVersion install spacy
	$getPermission pipVersion install gensim
	$getPermission pipVersion install wxpython
	$getPermission pipVersion install pillow
	$getPermission pipVersion install sqlalchemy
	$getPermission pipVersion install beautifulsoup
	$getPermission pipVersion install twisted
	$getPermission pipVersion install pygame
	$getPermission pipVersion install pyglet
	$getPermission pipVersion install pyqt
	$getPermission pipVersion install pygtk
	$getPermission pipVersion install scapy
	$getPermission pipVersion install pywin32
	$getPermission pipVersion install nose
	$getPermission pipVersion install ipython
	$getPermission pipVersion install math
	$getPermission pipVersion install datetime
	$getPermission pipVersion install psutil
	$getPermission pipVersion install dnspython
	$getPermission pipVersion install difflib
	$getPermission pipVersion install filecmp
	$getPermission pipVersion install smtplib
	$getPermission pipVersion install xlsxwriter
	$getPermission pipVersion install rrdtool
	$getPermission pipVersion install pyclamad
	$getPermission pipVersion install pexpect
	$getPermission pipVersion install ggihttprequesthandler
	$getPermission pipVersion install ansible
	$getPermission pipVersion install yaml
	$getPermission pipVersion install playbook
	$getPermission pipVersion install saltstack
	$getPermission pipVersion install func
	$getPermission pipVersion install builtin
	$getPermission pipVersion install exceptions
	$getPermission pipVersion install stat
	$getPermission pipVersion install string
	$getPermission pipVersion install cmath
	$getPermission pipVersion install operator
	$getPermission pipVersion install copy
	$getPermission pipVersion install types
	$getPermission pipVersion install gc
	$getPermission pipVersion install fileinput
	$getPermission pipVersion install tempfile
	$getPermission pipVersion install stringio
	$getPermission pipVersion install cstringio
	$getPermission pipVersion install mmap
	$getPermission pipVersion install userdict
	$getPermission pipVersion install userlist
	$getPermission pipVersion install errno
	$getPermission pipVersion install getopt
	$getPermission pipVersion install getpass
	$getPermission pipVersion install fnmatch
	$getPermission pipVersion install whrandom
	$getPermission pipVersion install cryopt
	$getPermission pipVersion install rotor
	$getPermission pipVersion install zlib
	$getPermission pipVersion install code
	$getPermission pipVersion install thread
	$getPermission pipVersion install commands
	$getPermission pipVersion install pipes
	$getPermission pipVersion install popen2
	$getPermission pipVersion install signal
	$getPermission pipVersion install array
	$getPermission pipVersion install struct
	$getPermission pipVersion install sdrlib
	$getPermission pipVersion install mashal
	$getPermission pipVersion install copy_reg
	$getPermission pipVersion install repr
	$getPermission pipVersion install base64
	$getPermission pipVersion install binhex
	$getPermission pipVersion install quopri
	$getPermission pipVersion install uu
	$getPermission pipVersion install binascii
	$getPermission pipVersion install xml.parsers.expat
	$getPermission pipVersion install sgmllib
	$getPermission pipVersion install htmllib
	$getPermission pipVersion install htmlentitydefs
	$getPermission pipVersion install dormatter
	$getPermission pipVersion install netrc
	$getPermission pipVersion install shlex
	$getPermission pipVersion install zipfile
	$getPermission pipVersion install gzip
	$getPermission pipVersion install rfc822
	$getPermission pipVersion install mimetools
	$getPermission pipVersion install mimewriter
	$getPermission pipVersion install mailbox
	$getPermission pipVersion install mailcap
	$getPermission pipVersion install mimetypes
	$getPermission pipVersion install packmail
	$getPermission pipVersion install mimify
	$getPermission pipVersion install multifile
	$getPermission pipVersion install socket
	$getPermission pipVersion install select
	$getPermission pipVersion install asyncore
	$getPermission pipVersion install asynchat
	$getPermission pipVersion install cookie
	$getPermission pipVersion install robotparser
	$getPermission pipVersion install ftplib
	$getPermission pipVersion install gopherlib
	$getPermission pipVersion install poplib
	$getPermission pipVersion install imaplib
	$getPermission pipVersion install telnetlib
	$getPermission pipVersion install nntplib
	$getPermission pipVersion install socketserver
	$getPermission pipVersion install basehttpserver
	$getPermission pipVersion install cgihttpserver
	$getPermission pipVersion install cgi
	$getPermission pipVersion install webbrowser
	$getPermission pipVersion install locale
	$getPermission pipVersion install unicodedata
	$getPermission pipVersion install ucnhash
	$getPermission pipVersion install imghdr
	$getPermission pipVersion install sndhdr
	$getPermission pipVersion install whatsound
	$getPermission pipVersion install aifc
	$getPermission pipVersion install sunau
	$getPermission pipVersion install sunaudio
	$getPermission pipVersion install wave
	$getPermission pipVersion install audiodev
	$getPermission pipVersion install winsound
	$getPermission pipVersion install anydbm
	$getPermission pipVersion install whichdb
	$getPermission pipVersion install shelve
	$getPermission pipVersion install dbhash
	$getPermission pipVersion install dbm
	$getPermission pipVersion install dumbdbm
	$getPermission pipVersion install gdbm
	$getPermission pipVersion install bdb
	$getPermission pipVersion install profile
	$getPermission pipVersion install pstats
	$getPermission pipVersion install tabnanny
	$getPermission pipVersion install fcntl
	$getPermission pipVersion install pwd
	$getPermission pipVersion install grp
	$getPermission pipVersion install nix
	$getPermission pipVersion install curses
	$getPermission pipVersion install termios
	$getPermission pipVersion install tty
	$getPermission pipVersion install resource
	$getPermission pipVersion install syslog
	$getPermission pipVersion install msvcrt
	$getPermission pipVersion install nt
	$getPermission pipVersion install _winreg
	$getPermission pipVersion install winreg
	$getPermission pipVersion install winreg
	$getPermission pipVersion install posix
	$getPermission pipVersion install dospath
	$getPermission pipVersion install macpath
	$getPermission pipVersion install ntpath
	$getPermission pipVersion install posixpath
	$getPermission pipVersion install strop
	$getPermission pipVersion install imp
	$getPermission pipVersion install new
	$getPermission pipVersion install pre
	$getPermission pipVersion install sre
	$getPermission pipVersion install py_compile
	$getPermission pipVersion install compileall
	$getPermission pipVersion install ihooks
	$getPermission pipVersion install linecache
	$getPermission pipVersion install macurl2path
	$getPermission pipVersion install tokenize
	$getPermission pipVersion install keyword
	$getPermission pipVersion install symbol
	$getPermission pipVersion install token
	$getPermission pipVersion install pyclbr
	$getPermission pipVersion install cmd
	$getPermission pipVersion install rexec
	$getPermission pipVersion install bastion
	$getPermission pipVersion install Bastion
	$getPermission pipVersion install readline
	$getPermission pipVersion install rlcompleter
	$getPermission pipVersion install statvfs
	$getPermission pipVersion install calendar
	$getPermission pipVersion install sched
	$getPermission pipVersion install statcache
	$getPermission pipVersion install grep
	$getPermission pipVersion install dircache
	$getPermission pipVersion install dircmp
	$getPermission pipVersion install cmp
	$getPermission pipVersion install cmpcache
	$getPermission pipVersion install util
	$getPermission pipVersion install soundex
	$getPermission pipVersion install timing
	$getPermission pipVersion install posixfile
	$getPermission pipVersion install bisect
	$getPermission pipVersion install knee
	$getPermission pipVersion install tzparse
	$getPermission pipVersion install regex
	$getPermission pipVersion install regsub
	$getPermission pipVersion install reconvert
	$getPermission pipVersion install regex_syntax
	$getPermission pipVersion install find
	$getPermission pipVersion install textwrap
	$getPermission pipVersion install stringprep
	$getPermission pipVersion install codecs
	$getPermission pipVersion install collections.abc
	$getPermission pipVersion install heapq
	$getPermission pipVersion install weakref
	$getPermission pipVersion install reprlib
	$getPermission pipVersion install numbers
	$getPermission pipVersion install fractions
	$getPermission pipVersion install decimal
	$getPermission pipVersion install stat
	$getPermission pipVersion install copyreg
	$getPermission pipVersion install marshal
	$getPermission pipVersion install sqlite3
	$getPermission pipVersion install zlib
	$getPermission pipVersion install bz2
	$getPermission pipVersion install lzma
	$getPermission pipVersion install tarfile
	$getPermission pipVersion install xdrlib
	$getPermission pipVersion install plistlib
	$getPermission pipVersion install hmac
	$getPermission pipVersion install optparser
	$getPermission pipVersion install platform
	$getPermission pipVersion install ctypes
	$getPermission pipVersion install concurrent
	$getPermission pipVersion install dummy_threading
	$getPermission pipVersion install _thread
	$getPermission pipVersion install _dummy_thread
	$getPermission pipVersion install ssl
	$getPermission pipVersion install email
	$getPermission pipVersion install html
	$getPermission pipVersion install wsgiref
	$getPermission pipVersion install http
	$getPermission pipVersion install smtpd
	$getPermission pipVersion install uuid
	$getPermission pipVersion install xmlrpc
	$getPermission pipVersion install ipaddress
	$getPermission pipVersion install audioop
	$getPermission pipVersion install chunk
	$getPermission pipVersion install colorsys
	$getPermission pipVersion install ossaudiodev
	$getPermission pipVersion install gettext
	$getPermission pipVersion install turtle
	$getPermission pipVersion install tkinter
	$getPermission pipVersion install tkinter.ttk
	$getPermission pipVersion install pydoc
	$getPermission pipVersion install doctest
	$getPermission pipVersion install unittest
	$getPermission pipVersion install test
	$getPermission pipVersion install venv
	$getPermission pipVersion install faulthandler
	$getPermission pipVersion install trace
	$getPermission pipVersion install sysconfig
	$getPermission pipVersion install main
	$getPermission pipVersion install warnings
	$getPermission pipVersion install contextlib
	$getPermission pipVersion install abc
	$getPermission pipVersion install atexit
	$getPermission pipVersion install future
	$getPermission pipVersion install inspect
	$getPermission pipVersion install site
	$getPermission pipVersion install fpectl
	$getPermission pipVersion install distutils
	$getPermission pipVersion install codeop
	$getPermission pipVersion install zipimport
	$getPermission pipVersion install pkgutil
	$getPermission pipVersion install modulefinder
	$getPermission pipVersion install runpy
	$getPermission pipVersion install importlib
	$getPermission pipVersion install ast
	$getPermission pipVersion install symtable
	$getPermission pipVersion install tabnany
	$getPermission pipVersion install formatter
	$getPermission pipVersion install msilib
	$getPermission pipVersion install spwd
	$getPermission pipVersion install crypt
	$getPermission pipVersion install pty
	$getPermission pipVersion install nis
	$getPermission pipVersion install opencv-python
	$getPermission pipVersion install mysql-python
	$getPermission pipVersion install agate
	$getPermission pipVersion install agate-dbf
	$getPermission pipVersion install agate-excel
	$getPermission pipVersion install agate-sql
	$getPermission pipVersion install Babel
	$getPermission pipVersion install csvkit
	$getPermission pipVersion install dbfread
	$getPermission pipVersion install et-xmlfile
	$getPermission pipVersion install isodate
	$getPermission pipVersion install jdcal
	$getPermission pipVersion install leather
	$getPermission pipVersion install openpyxl
	$getPermission pipVersion install parsedatetime
	$getPermission pipVersion install python-slugify
	$getPermission pipVersion install pytimeparse
	$getPermission pipVersion install pytz
	$getPermission pipVersion install six
	$getPermission pipVersion install SQLAlchemy
	$getPermission pipVersion install text-unidecode
	$getPermission pipVersion install xlrd
	$getPermission pipVersion install -lxc
	$getPermission pipVersion install lxc
	$getPermission pipVersion install cached-property
	$getPermission pipVersion install chardet
	$getPermission pipVersion install docker
	$getPermission pipVersion install docker-compose
	$getPermission pipVersion install docker-pycreds
	$getPermission pipVersion install dockerpty
	$getPermission pipVersion install docopt
	$getPermission pipVersion install httplib2
	$getPermission pipVersion install idna
	$getPermission pipVersion install jsonschema
	$getPermission pipVersion install NetEase-MusicBox
	$getPermission pipVersion install openshot-qt
	$getPermission pipVersion install pip
	$getPermission pipVersion install pycryptodomex
	$getPermission pipVersion install PyQt5
	$getPermission pipVersion install PyQt5-sip
	$getPermission pipVersion install PySocks
	$getPermission pipVersion install PyYAML
	$getPermission pipVersion install pyzmq
	$getPermission pipVersion install requests-cache
	$getPermission pipVersion install setuptools
	$getPermission pipVersion install six
	$getPermission pipVersion install texttable
	$getPermission pipVersion install websocket-client
	$getPermission pipVersion install wheel
	$getPermission pipVersion install slsx2csv
	$getPermission pipVersion install networkx
	$getPermission pipVersion install mgzip
	
	i=`expr $i + 1`
done
